version: "3.7"
services:
  php:
    build:
      context: ./
      dockerfile: .docker/Dockerfile
    container_name: ICStorm-app
    working_dir: /var/www
    volumes:
      - ./:/var/www

  nginx:
    image: nginx:latest
    container_name: ICStorm-nginx
    restart: always
    depends_on:
      - php
    ports:
      - "80:80"
    volumes:
      - ./:/var/www
      - ./.docker/nginx.conf:/etc/nginx/conf.d/default.conf