name: CI

on:
  push:
    branches:
      - main
      - dev
  pull_request:

jobs:
  #  phpcs:
  #    runs-on: ubuntu-latest
  #    steps:
  #      - uses: actions/checkout@v2
  #
  #      - name: Setup PHP Action with phpcs
  #        uses: shivammathur/setup-php@v2
  #        with:
  #          php-version: '8.1'
  #          tools: phpcs
  #          coverage: none
  #
  #      - name: Validate composer.json and composer.lock
  #        run: composer validate --strict
  #
  #      - name: Get composer cache directory
  #        id: composer-cache
  #        run: echo "::set-output name=dir::$(composer config cache-files-dir)"
  #
  #      - name: Cache Composer packages
  #        uses: actions/cache@v3
  #        with:
  #          path: ${{ steps.composer-cache.outputs.dir }}
  #          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
  #          restore-keys: ${{ runner.os }}-composer-
  #
  #      - name: Install dependencies
  #        run: composer install --prefer-dist --no-progress
  #
  #      - name: Run PHPCS
  #        run: phpcs

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions: ['8.2', '8.3']
    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP ${{ matrix.php-versions }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: simplexml
          coverage: none

      - name: Get composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache Composer packages
        uses: actions/cache@v3
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: Run test suite
        run: vendor/bin/phpunit

  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP with tools
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          extensions: simplexml

      - name: Get composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache Composer packages
        uses: actions/cache@v4
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: Run test suite with coverage
        run: vendor/bin/phpunit --coverage-clover clover.xml

      - name: Upload coverage
        uses: paambaati/codeclimate-action@v5
        env:
          CC_TEST_REPORTER_ID: 9e282ada616888f3a9fc652ee98ccb47651d1e105e9a4637a60efaf6d66fe71f
        with:
          coverageLocations: ${{github.workspace}}/clover.xml:clover
          debug: true